### ISSUE TITLE
Typescript Errors in Visual Studio but project compiles and runs

### ISSUE THREAD

**Issue by prindacerk** [vuejs/vue-class-component#197]
I am a beginner learning Vue with .NET Core environment. I created a project using SPA Templates and it runs fine. But it comes preset with older Vue and other components. So I updated my packages. There were some tweaks I had to do to get it working but it works fine now. 

You can see the repository here. https://github.com/prindacerk/corevue

Eventhough the project compiles and runs, in Visual Studio, there are Typescript errors for all the .ts files. It won't prevent the compilation but the error shows in all the files. I googled and came across this one. But this issue is reported to be fixed on 2.5.3. https://github.com/vuejs/vue-class-component/issues/181

But as shown in the screenshot, it still shows in 2.5.8.
<img width="1871" alt="ts error in vs" src="https://user-images.githubusercontent.com/4536573/33154180-a63e7ade-d03a-11e7-9f61-b033f521dbcb.png">

Please let me know why it is happening and how to fix it.

**Comment by HerringtonDarkholme** [comment]
Probably it's visual studio's issue. Can you compile it in webpack and tsloader?

**Comment by prindacerk** [comment]
I can compile with webpack. It builds the main.js and vendor files. But on Visual studio, every ts file has an error like this at Component and Vue.

**Comment by HerringtonDarkholme** [comment]
@prindacerk  Can you try it in vscode?

**Comment by prindacerk** [comment]
I don't have Visual Studio Code installed in this PC. I will test it when I go home where I can access my laptop.

**Comment by prindacerk** [comment]
I don't know if this is relevant or not. I also can't compile webpack if I use the **Task Runner Explorer** to execute the webpack run method. Following is the response when I run webpack using TRE.

`D:\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue> cmd /c SET NODE_ENV=development&& webpack --color
Hash: f9f70cf1dfe77d7188a4
Version: webpack 2.7.0
Child
    Hash: f9f70cf1dfe77d7188a4
    Time: 1685ms
          Asset     Size  Chunks             Chunk Names
        main.js  30.5 kB       0  [emitted]  main
    main.js.map  18.7 kB       0  [emitted]  main
    
    ERROR in ./ClientApp/components/home/home.vue.html
    Module build failed: SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\vue-loader\index.js:1:18)
        at Module._compile (module.js:397:26)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at loadLoader (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:179:3)
        at NormalModule.build (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:268:15)
        at Compilation.buildModule (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:146:10)
        at factoryCallback (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:329:11)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:253:5
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:99:14
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:268:11
        at NormalModuleFactory.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:272:13)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:74:11
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:205:8
        at nextTickCallbackWith0Args (node.js:452:9)
        at process._tickCallback (node.js:381:13)
     @ ./ClientApp/boot.ts 7:28-70
    
    ERROR in ./ClientApp/components/counter/counter.vue.html
    Module build failed: SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\vue-loader\index.js:1:18)
        at Module._compile (module.js:397:26)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at loadLoader (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:179:3)
        at NormalModule.build (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:268:15)
        at Compilation.buildModule (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:146:10)
        at factoryCallback (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:329:11)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:253:5
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:99:14
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:268:11
        at NormalModuleFactory.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:272:13)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:74:11
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:205:8
        at nextTickCallbackWith0Args (node.js:452:9)
        at process._tickCallback (node.js:381:13)
     @ ./ClientApp/boot.ts 8:35-83
    
    ERROR in ./ClientApp/components/fetchdata/fetchdata.vue.html
    Module build failed: SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\vue-loader\index.js:1:18)
        at Module._compile (module.js:397:26)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at loadLoader (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:179:3)
        at NormalModule.build (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:268:15)
        at Compilation.buildModule (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:146:10)
        at factoryCallback (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:329:11)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:253:5
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:99:14
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:268:11
        at NormalModuleFactory.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:272:13)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:74:11
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:205:8
        at nextTickCallbackWith0Args (node.js:452:9)
        at process._tickCallback (node.js:381:13)
     @ ./ClientApp/boot.ts 9:37-89
    
    ERROR in ./ClientApp/components/todos/todos.vue.html
    Module build failed: SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\vue-loader\index.js:1:18)
        at Module._compile (module.js:397:26)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at loadLoader (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:179:3)
        at NormalModule.build (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:268:15)
        at Compilation.buildModule (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:146:10)
        at factoryCallback (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:329:11)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:253:5
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:99:14
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:268:11
        at NormalModuleFactory.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:272:13)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:74:11
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:205:8
        at nextTickCallbackWith0Args (node.js:452:9)
        at process._tickCallback (node.js:381:13)
     @ ./ClientApp/boot.ts 10:33-77
    
    ERROR in ./ClientApp/components/app/app.vue.html
    Module build failed: SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\vue-loader\index.js:1:18)
        at Module._compile (module.js:397:26)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at loadLoader (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:179:3)
        at NormalModule.build (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModule.js:268:15)
        at Compilation.buildModule (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:146:10)
        at factoryCallback (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\Compilation.js:329:11)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:253:5
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:99:14
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:268:11
        at NormalModuleFactory.<anonymous> (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\tapable\lib\Tapable.js:272:13)
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:74:11
        at D:\Users\Developer\Documents\Visual Studio 2017\Projects\VueSamples\CoreVue\node_modules\webpack\lib\NormalModuleFactory.js:205:8
        at nextTickCallbackWith0Args (node.js:452:9)
        at process._tickCallback (node.js:381:13)
     @ ./ClientApp/boot.ts 15:36-76
Process terminated with code 2.`

**Comment by prindacerk** [comment]
The funny thing is, both these issues don't exist in the original SPA Template with the following package versions.
```
{
  "name": "vue-template",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {
    "@types/webpack-env": "^1.13.0",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "^3.1.3",
    "bootstrap": "^3.3.7",
    "css-loader": "^0.25.0",
    "event-source-polyfill": "^0.0.7",
    "extract-text-webpack-plugin": "^2.1.2",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.2.1",
    "style-loader": "^0.13.2",
    "typescript": "^2.3.4",
    "url-loader": "^0.5.9",
    "vue": "^2.3.4",
    "vue-loader": "^11.3.4",
    "vue-property-decorator": "^5.1.0",
    "vue-router": "^2.6.0",
    "vue-template-compiler": "^2.3.4",
    "webpack": "^2.6.1",
    "webpack-hot-middleware": "^2.18.0"
  }
}
```
The Task Runner Explorer executes without any problem and the TypeScript doesn't show any errors and it runs fine.

**Comment by HerringtonDarkholme** [comment]
@ktsn it has already been off topic. I'm sure this is visual studio configuration issue.

**Comment by prindacerk** [comment]
@HerringtonDarkholme So should I contact Visual Studio support regarding this? Is that Task Runner Explorer build error caused by VS or Webpack or Typescript or VueJs?

**Comment by ktsn** [comment]
This looks not related with vue-class-component.
We encourage you to use [our forum](http://forum.vuejs.org/) or [community chat](https://chat.vuejs.org/) to ask your questions. Thanks!

**Comment by prindacerk** [comment]
@ktsn Apologies. I didn't realize there's a forum and community chat. Will follow up on this in there and see. I do think it has something to do with Visual Studio and Typescript but it is only having this problem on Vue.js project. Angular project on Typescript is working fine. So that's why I thought to reach out here and see before I ask others.

**Comment by dgwaldo** [comment]
@prindacerk We are having the issue as well.  Did you find out what the issue was? Interestingly it does not seem to happen in VS Code.  VS has typically been pretty solid on the TS definition issues. My experience has been that if VS says somethings screwy with your typescript def, then it's probably right. @ktsn The update to vue, not VS brought this about, so not sure how you logic out that it's not a vue problem.  Suspect your own stuff first.

**Comment by prindacerk** [comment]
@dgwaldo I reported to Visual Studio and they said nothing was wrong with VS. I updated to the latest version as well. However, the javascript errors in my screenshot disappeared after I installed/updated the extensions they have for TypeScript in Visual Studio and Vue.js. 

I think I installed these extensions.
1) TypeScript Build for Microsoft Visual Studio
2) TypeScript for Microsoft Visual Studio
3) Vue.js Pack 2017

After installing them, Visual Studio recognized the code and didn't show it as an error anymore.

I am still stuck on the WebPack compile using Task Runner Explorer. That still throws an error with these versions. I don't have a solution for that yet.

**Comment by mzhukovs** [comment]
What is the solution for this? Using .NET core 2 template dotnet new vue I get VS2017 errors out of the box but it actually does run fine and work (even debugging) in the files that contain the "errors", e.g. in counter.ts tells me it can't find the modules 'vue' and '-vue-property-decorator' on the 2 import statements and then for the @Component tag it says "not assignable to type VueClass", plesae help

**Comment by tbsvttr** [comment]
Same problem here with Visual Studio Code.

**Comment by ahmettahasakar** [comment]
Has anyone find a solution for this? Installing vue pack and typescript sdk didn't help like @prindacerk mentioned

**Comment by prindacerk** [comment]
Visual Studio SPA Templates has officially removed Vue from it's listing now. They are focusing on Angular.
However, I did manage to get a template built for myself that works fine.
@ahmettahasakar Did you install all the plugins I mentioned? 

If you want, try this repository and see if it builds in your PC. This is my Vue.Js template for ASP.NET Core on latest version.
https://github.com/prindacerk/core.vue

Please let me know if it is not working. If not, then reason. If it works, check what is different in your project to cause the issue. Mainly the package versions.

**Comment by ahmettahasakar** [comment]
I coulsnt find a typescript build extension. The only typescript extension i found just installs typeacript sdk.
As for the template being removed. Do you know why? I could still install and use it. It works without errors during runtime. But visual studio just gives the errors mentioned. I couldnt find a way fix the errors. But is still works.

On Fri, Jun 8, 2018 at 0:34, prindacerk <notifications@github.com> wrote:
Visual Studio SPA Templates has officially removed Vue from it's listing now. They are focusing on Angular.
However, I did manage to get a template built for myself that works fine.
@ahmettahasakar [https://github.com/ahmettahasakar] Did you install all the plugins I mentioned?

If you want, try this repository and see if it builds in your PC. This is my Vue.Js template for ASP.NET Core on latest version.
https://github.com/prindacerk/core.vue [https://github.com/prindacerk/core.vue]

Please let me know if it is not working. If not, then reason. If it works, check what is different in your project to cause the issue. Mainly the package versions.

**Comment by prindacerk** [comment]
@ahmettahasakar Typescript Build is not an extension. I apologize. I meant in the Project Properties, there's a tab called "Typescript Build". And make sure the Typescript version matches the version selected. Or select "Use Latest available" which will automatically use tsconfig.json.

As for why they removed the Template, it's because they couldn't maintain it as their resource is limited. You can read about it [here](https://github.com/aspnet/Announcements/issues/289) and the discussion about it [here](https://github.com/aspnet/JavaScriptServices/issues/1522)

Try downloading the project in the repository I gave before. And see if it is showing any errors or not.
