### ISSUE TITLE
mixins helper breaks SSR

### ISSUE THREAD

**Issue by zelid** [vuejs/vue-class-component#232]
Mixing helper doesn't work well with standard Vue's SSR approach (`entry-client.ts`, `entry-server.ts`)

I'm trying to port a global mixin from official SSR JavaScript example to TypeScript
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-client.js#L11
```
// a global mixin that calls `asyncData` when a route component's params change
Vue.mixin({
  beforeRouteUpdate (to, from, next) {
    const { asyncData } = this.$options
    if (asyncData) {
      asyncData({
        store: this.$store,
        route: to
      }).then(next).catch(next)
    } else {
      next()
    }
  }
})
```

I didn't get to porting from JS to TS because even simplest mixins doesn't work when used on the server. 
I've started from the simplest mixins like:
```
// Hellowable Mixin
// Writes hello to console once created
@Component
export class Hellowable extends Vue  {
  created(): void {
      this.hello();
  }
  hello(): void {
    console.log('!!!!!!!!!!!!! hello from mixin !!!!!!!!!!!!!!!');
  }
}
```

```
// A mixin from the official vue-class-component docs
@Component
export class MyMixin extends Vue {
  mixinValue = 'Hello'
}
```

These mixins are used in single file Vue components together with `vue-class-component` like:
```
<template>
<div>
    <h1>Secure</h1>
    <input type="text" v-model="content" />
</div>
</template>

<script lang="ts">
import Vue from "Vue";
import axios from "axios";
import Component, { mixins } from "vue-class-component";

import { Hellowable, MyMixin } from "../assets/entry-client";

@Component
export default class SecureView extends mixins(MyMixin) {
  message: string = "Hello!";
  content: string = "Default Content";

  created(): void {
    console.log("created");
  }

  getToken(): string {
    let token = "";
    if (Vue.prototype.$isServer) {
      console.log("SERVER:");
      token = this.$ssrContext.cookies.token;
    } else {
      console.log("BROWSER:");
      token = localStorage.getItem("token") || ""; //this.$cookies.token;
    }
    console.log("token: " + token);
    return token;
  }
}
</script>
```

When rendered on the server it gives 500 error:
```
[vue-router] Failed to resolve async component default: ReferenceError: window is not defined
[vue-router] uncaught error during route navigation:
ReferenceError: window is not defined
    at Object.44 (2.server-bundle.js:8200:1)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.36 (2.server-bundle.js:50:79)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.31 (2.server-bundle.js:9:184)
    at __webpack_require__ (server-bundle.js:27:30)
    at server-bundle.js:841:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
error during render : /secure
ReferenceError: window is not defined
    at Object.44 (assets/entry-client.ts:71:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 2a1063e9f36ca15936e2:25:0)
    at Object.36 (2.server-bundle.js:50:79)
    at __webpack_require__ (webpack:/webpack/bootstrap 2a1063e9f36ca15936e2:25:0)
    at Object.31 (2.server-bundle.js:9:184)
    at __webpack_require__ (webpack:/webpack/bootstrap 2a1063e9f36ca15936e2:25:0)
    at server-bundle.js:841:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

package.js
```
{
  "name": "components-ssr-vuetify",
  "description": "A Vue.js project",
  "author": "",
  "version": "0.0.1",
  "scripts": {
    "start:dev": "./node_modules/.bin/ts-node ./server",
    "start:debug": "./node_modules/.bin/ts-node-dev -F --type-check --inspect=5859 --ignore false ./server",
    "start:prod": "cross-env NODE_ENV=production node ./dist/server",
    "dev": "node server",
    "start": "cross-env NODE_ENV=production node server",
    "build": "rimraf dist && npm run build:client && npm run build:server",
    "build:client": "cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules",
    "build:server": "cross-env NODE_ENV=production webpack --config build/webpack.server.config.js --progress --hide-modules"
  },
  "engines": {
    "node": ">=7.0",
    "npm": ">=4.0",
    "typescript": "*"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "compression": "^1.6.2",
    "cookie-parser": "^1.4.3",
    "cross-env": "^5.1.4",
    "es6-promise": "^4.1.0",
    "express": "^4.16.2",
    "iview": "^2.10.1",
    "lru-cache": "^4.1.2",
    "serialize-javascript": "^1.4.0",
    "serve-favicon": "^2.4.5",
    "vue": "^2.5.14",
    "vue-class-component": "^6.2.0",
    "vue-cookie": "1.1.4",
    "vue-loader": "^14.2.1",
    "vue-router": "^3.0.1",
    "vue-server-renderer": "^2.5.14",
    "vue-ssr-webpack-plugin": "^3.0.0",
    "vue-style-loader": "^4.0.2",
    "vue-template-compiler": "^2.5.14",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.0.0-beta.40",
    "@types/core-js": "^0.9.46",
    "@types/node": "^9.4.7",
    "autoprefixer": "^7.1.1",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-import": "^1.6.6",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-regenerator": "^6.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "css-loader": "^0.28.10",
    "eventsource-polyfill": "^0.9.6",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "highlight.js": "^9.12.0",
    "html-webpack-plugin": "^3.0.6",
    "iview-loader": "^1.1.0",
    "less": "^3.0.1",
    "less-loader": "^4.0.6",
    "mini-css-extract-plugin": "^0.2.0",
    "node-sass": "^4.7.2",
    "optimize-css-assets-webpack-plugin": "^4.0.0",
    "pug": "^2.0.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "script-ext-html-webpack-plugin": "^1.8.8",
    "style-loader": "^0.20.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "sw-precache-webpack-plugin": "^0.11.4",
    "ts-loader": "^3.5.0",
    "ts-node": "5.0.1",
    "ts-node-dev": "1.0.0-pre.18",
    "tslint": "^5.9.1",
    "tslint-loader": "^3.6.0",
    "typescript": "^2.7.2",
    "uglifyjs-webpack-plugin": "^1.2.2",
    "url-loader": "^1.0.1",
    "webpack": "^3.11.0",
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-cli": "^2.0.10",
    "webpack-dev-middleware": "^2",
    "webpack-hot-middleware": "^2.21.2",
    "webpack-merge": "^4.1.2",
    "webpack-node-externals": "^1.6.0"
  }
}
```

Any idea how to make  TypeScript'ed `vue-class-component` working with Vue's server side rendering and global mixings for asyncData?

**Comment by ktsn** [comment]
Hi, could you provide minimal reproduction by using github repo? Thanks!

**Comment by HerringtonDarkholme** [comment]
I don't think this is related to class component. The error is clearly window is not defined and we don't have reference to it. 

Please provide a reproduction that does work with plain object style API and breaks with class component.

If you have questions, please refer to stackoverflow.

**Comment by zelid** [comment]
I will try to play a bit and provide the repo soon.

Meanwhile found here a different [TypeScript Vue Mixin approach with server side rendering](https://github.com/zyml/nuswhispers-vue/tree/master/src/mixins) a bit different approach for Vue TypeScript mixins based on extending `ComponentOptions<Vue>` like:
```
const serverMixin: ComponentOptions<Vue> = {
  created() {
    const meta = getMeta(this) || defaultMeta(this);
    this.$ssrContext.meta = generateMetaHtml(meta);
  },
};

const clientMixin: ComponentOptions<Vue> = {
  mounted() {
    // Naive implementation.
    // Remove all existing generated meta tags, then add all in.
    Array.prototype.forEach.call(
      document.querySelectorAll(`[${mixinAttribute}]`),
      (e: Element) => {
        if (e.parentNode) {
          e.parentNode.removeChild(e);
        }
      },
    );

    const meta = getMeta(this);
    if (meta) {
      const headElement = document.querySelector('head');

      if (!headElement) {
        return;
      }

      meta.map((m: Dictionary<string>) => {
        const ele: Element = document.createElement('meta');

        map(m, (value: string, key: string) => ele.setAttribute(key, escapeHtml(value)));
        ele.setAttribute(mixinAttribute, '');

        headElement.appendChild(ele);
      });
    }
  },
};

export default process.env.VUE_ENV === 'server' ? serverMixin : clientMixin;
```

**Comment by zelid** [comment]
This is related to providing the repository, I'm refactoring some JS to TS to make things clearer and can't solve "vue-class-component/lib/index.d.ts" casting issue with the function that used to work before:

```
/**
 * Wrap native JavaScript classes as Vue components and expose static
 * route methods for server-side rendering.
 */
function ASyncComponent<U extends Vue>(options: ComponentOptions<U>): <V extends VueClass>(target: V) => V {
  return (target: VueClass) => {
      
    const wrappedComponent = Component(options)(target) as ASyncComponent;

    $staticMethods.forEach((method) => {
      if (target.prototype[method]) {
        wrappedComponent[method] = target.prototype[method];
      }
    });

    return wrappedComponent;
  };
}
```

The type error says:
```
[ts]
Type '(target: VueClass) => ASyncComponent' is not assignable to type '<V extends VueClass>(target: V) => V'.
  Type 'ASyncComponent' is not assignable to type 'V'.
(parameter) target: (new () => Vue) & VueConstructor<Vue>
```
How to make the function listed above to comply with `declare function Component<V extends Vue>(options: ComponentOptions<V> & ThisType<V>): <VC extends VueClass<V>>(target: VC) => VC;`?

**Comment by zelid** [comment]
@ktsn, @HerringtonDarkholme thanks for fast replies it really helped to figure out the issue in non `vue-class-component`

This is what actually helped:

```
type VueClass<Vue> = { new(): Vue } & typeof Vue;
```

```
export declare interface ASyncComponent extends VueClass<Vue> {
  fetchInitialData(props: InitialDataProps): Promise<any>;
}
```

```
/**
 * Wrap native JavaScript classes as Vue components and expose static
 * route methods for server-side rendering.
 */
function ASyncComponent<U extends Vue, V extends VueClass<U & Vue>>(options: ComponentOptions<U>): (target: V) => V {
  return (target: V) => {
    const wrappedComponent = Component(options)(target) as V;
    $staticMethods.forEach((method) => {
      if (target.prototype[method]) {
        wrappedComponent[method] = target.prototype[method];
      }
    });
    return wrappedComponent;
  };
}
```

And vue-class-component works fine now with SSR using this approach.
The custom "global mixin that calls `asyncData`" for SSR is not needed anymore since ASyncComponent  does the job.

**Comment by zelid** [comment]
Just for a case, this is what makes  `vue-class-component` work well with SSR:

```
// ASyncComponent.ts

import Vue, { ComponentOptions } from 'vue';
import Component from 'vue-class-component';
import { Route } from 'vue-router';
import { Store } from '../store';

type VueClass<Vue> = { new(): Vue } & typeof Vue;

Component.registerHooks([
  'beforeRouteEnter',
  'beforeRouteUpdate',
  'beforeRouteLeave',
  'title',
  'meta',
]);

export const $staticMethods = [
  'fetchInitialData',
];

export interface InitialDataProps {
  store: Store;
  route: Route;
}

export declare interface ASyncComponent extends VueClass<Vue> {
  fetchInitialData(props: InitialDataProps): Promise<any>;
}

/**
 * Wrap native JavaScript classes as Vue components and expose static
 * route methods for server-side rendering.
 */
function ASyncComponent<U extends Vue, V extends VueClass<U & Vue>>(options: ComponentOptions<U>): (target: V) => V {
  return (target: V) => {
    const wrappedComponent = Component(options)(target) as V;
    $staticMethods.forEach((method) => {
      if (target.prototype[method]) {
        wrappedComponent[method] = target.prototype[method];
      }
    });
    return wrappedComponent;
  };
}

export default ASyncComponent;
```

```
// entry-server.ts
import Vue from 'vue';
import { createApp } from './app';
import { ASyncComponent } from '../components/ASyncComponent';

export default (context: any) => {
  return new Promise((resolve, reject) => {
    const { app, router, store } = createApp();

    router.push(context.url);

    router.onReady(() => {
      const matchedComponents = router.getMatchedComponents();
      if (!matchedComponents.length) {
        reject({ code: 404 });
      }

      // Include fetching categories + top tags for navigation.
      Promise.all([
        // store.dispatch('getCategories') as Promise<any>,
        // store.dispatch('getTags') as Promise<any>,
        ...matchedComponents.map((c) => {
          if ((c as ASyncComponent).fetchInitialData) {
            return (c as ASyncComponent).fetchInitialData({
              store,
              route: router.currentRoute,
            });
          }
        }),
      ]).then(() => {
        context.state = store.state;
        resolve(app);
      }).catch(reject);
    }, reject);
  });
};
```

Another TypeScript + SSR integration (no vue-class-component used) is can be found here:
[Vue+SSR+TypeScript - no class component](https://github.com/linzebin/vue-ssr-typescript/blob/master/src/entry-server.ts)
Just for a case if anyone get the similar SSR issues I had. Official Vue's documentation provides information and example for JavaScript version of SSR only.
