### ISSUE TITLE
this.$t is not a function in a class component

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-class-component#505]
### Subject of the issue

I have the following component

```vue
<template>
  <div>{{someData}}</div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class App extends Vue {
  private someData = this.$t("message");
}
</script>
```

and the following unit test

```js
import { mount } from '@vue/test-utils'
import App from '@/App.vue'

describe('App.vue', () => {
  it('some unit test', () => {
    const wrapper = mount(App, {
      mocks: {
        $t: (key: string) => key
      }
    });
    expect(wrapper).toBeDefined();
  })
})
```

When running this unit test, it fails with the following error:

```
 FAIL  tests/unit/example.spec.ts
  HelloWorld.vue
    ✕ some unit test (22ms)

  ● HelloWorld.vue › some unit test

    TypeError: this.$t is not a function

       8 | @Component
       9 | export default class App extends Vue {
    > 10 |   private someData = this.$t("message");
         | ^
      11 | }
      12 | </script>
      13 | 

      at new App (src/App.vue:10:1)
      at collectDataFromConstructor (node_modules/vue-class-component/dist/vue-class-component.common.js:165:14)
      at VueComponent.data (node_modules/vue-class-component/dist/vue-class-component.common.js:227:14)
      at getData (node_modules/vue/dist/vue.runtime.common.dev.js:4732:17)
      at initData (node_modules/vue/dist/vue.runtime.common.dev.js:4689:7)
      at initState (node_modules/vue/dist/vue.runtime.common.dev.js:4628:5)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4987:5)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5134:12)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:3277:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3108:45)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:13991:21)
      at Object.<anonymous> (tests/unit/example.spec.ts:6:21)
```

### Steps to reproduce

Just run unit tests in this project:
[i18n-test.zip](https://github.com/vuejs/vue-test-utils/files/5797219/i18n-test.zip)

### Expected behaviour

Error `this.$t is not a function` should not occur. The `$t` function is mocked.

### Actual behaviour

An error `this.$t is not a function` is thrown.

### Additional context

If I convert `someData` to computed property, like this:

```vue
<template>
  <div>{{someData}}</div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class App extends Vue {
  private get someData() {
    return this.$t("message");
  }
</script>
```

the error is gone.

**Comment by Mikilll94** [comment]
@kaorun343 
https://github.com/vuejs/vue-test-utils/issues/1767#issuecomment-761301172

As you can see this is rather a bug in `vue-class-components` than in `vue-test-utils`.

**Comment by lmiller1990** [comment]
Does this work in a browser with the real `$t`? The problem is only when mocking `$t`?

**Comment by Mikilll94** [comment]
@lmiller1990 
In browser it is working. You can check this in my repro project. Only unit tests are failing.

**Comment by lmiller1990** [comment]
I am guessing VCC does some transform first, then VTU applies the mock `$t`, at which point it is too late.

I would recommend using `data` or `computed` as a work-around in the meantime.

Are you interested in investigating this bug/making a PR?

**Comment by Mikilll94** [comment]
@lmiller1990 
In the meantime I was debugging this for a while. It seems that `vue-class-component` overrides the class constructor and transforms property initializers into `data` in Vue component. This is happening in this function:
https://github.com/vuejs/vue-class-component/blob/16433462b40aefecc030919623f17b0ec9afe61c/src/data.ts#L5

If you debug `vm` variable you can see that when running unit tests, it is missing `_i18n` property. In the browser this property is present.

BTW. accessing `this` stuff in property initializers is a valid functionality of VCC. You check this here:
https://github.com/vuejs/vue-class-component/issues/432
https://github.com/vuejs/vue-class-component/pull/434

**Comment by lmiller1990** [comment]
Interesting. I suppose this makes sense. Class Component -> VCC transform -> VTU  $mocks. By the time $mocks happens, it is too late and the component is using whatever `this.$i18n` was at the time of the transform.

**Comment by Mikilll94** [comment]
@lmiller1990 

> Interesting. I suppose this makes sense. Class Component -> VCC transform -> VTU $mocks. By the time $mocks happens, it is too late and the component is using whatever this.$i18n was at the time of the transform. It expects $t to exist when VCC does it's transform, since it doesn't, boom.

When the mocking exactly happens in vue-test-utils? (you can show this in the source code) Does mocking occur after creating a component? If yes, then this is problematic for class components, because this `Component.prototype._init` function is executed before creating a component. This function transforms the property initializers to the `data` object.

Could you check the VCC source code to see if there is any solution to this? Maybe this can be fixed in VCC source code?

> An alternative would be using a createLocalVue, where you install a mocked $i18n. A bit more boilerplate, but you could make a function. Does that make sense?

Could you show an example?

**Comment by lmiller1990** [comment]
The mocking happens [here](https://github.com/vuejs/vue-test-utils/blob/3536ade41546a9a858bdee0b2a1f0928c156c672/packages/create-instance/add-mocks.js#L24). `createInstance` is ultimately called [when mount is called](https://github.com/vuejs/vue-test-utils/blob/3536ade41546a9a858bdee0b2a1f0928c156c672/packages/test-utils/src/mount.js#L32). The class component transform is applied far before this - it's all compiled to a regular object before it's even passed into `mount`.

I don't see a way to fix this by patching VCC. 

> Could you show an example

Looks like my idea doesn't work. I thought I could do something like this:

```ts
class MockPlugin {
  static install(Vue: any) {
    Vue.$t = (key: string) => key
  }
}

const localVue = createLocalVue()
localVue.use(MockPlugin)

describe('App.vue', () => {
  it('some unit test', () => {
    const wrapper = mount(App, {
      localVue,
      mocks: {
        $t: (key: string) => key
      }
    });
    expect(wrapper).toBeDefined();
  })
})
```

But the result is the same. Hm.

**Comment by lmiller1990** [comment]
Ok... this worked (webpack + mocha combo):

```ts
import { expect } from 'chai'
import Vue from 'vue'
import { mount, createLocalVue } from '@vue/test-utils'
import App from '@/App.vue'

class i18n {
  static install(Vue: any) {
    Vue.prototype.$t = (key: string) => key
  }
}

Vue.use(i18n)

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const wrapper = mount(App)
    console.log(wrapper.html())
  })
})
```

**Comment by ktsn** [comment]
A repro excluded the dep to vue-test-utils would be:

```ts
    @Component
    class Base extends Vue {
      test() {
        return 'base'
      }
    }

    @Component
    class Test extends Base {
      result = this.test()
    }

    const vm = new Test()
    expect(vm.result).to.equal('base')

    const Replaced = Vue.extend()
    Replaced.prototype.test = () => 'replaced'

    const replaced: Test = new (Replaced.extend({
      ...(Test as any).options,
    }))()
    expect(replaced.result).to.equal('replaced')
```

We could replace the prototype of the original constructor with the one of `localVue` in [`collectDataFromConstructor`](https://github.com/vuejs/vue-class-component/blob/master/src/data.ts#L5) but I'm not very sure about it and if it is really a good idea. I'll need more time to take a look...

**Comment by lmiller1990** [comment]
I thought about this too but I'm also unsure. We should also think about how this works in vue-class-component-next and vue-test-utils-next. VTU-next has the exact same problem but does *not* use the `localVue`. Whatever solution we come up with should work there, too.

**Comment by ygj6** [comment]
hope it helps you.
```js
@Component
export default class App extends Vue {
  private someData();
  created() {
     this.someData = this.$t("message");
   }
}
 
```

**Comment by Mikilll94** [comment]
@ktsn 
Please take a look at these comments:
https://github.com/vuejs/vue-test-utils/issues/1767#issuecomment-767597984
https://github.com/vuejs/vue-test-utils/issues/1767#issuecomment-769596262
