### ISSUE TITLE
not work in nuxt3

### ISSUE THREAD

**Issue by n4an** [vuejs/vue-class-component#570]
not work in nuxt3

**Comment by jimhucksly** [comment]
add option
```
{
 "type": "module"
}
```

in top-level of package.json fie

**Comment by jaybeecave** [comment]
True, looks related to SSR however.

```

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async __instantiateModule__ (file:///Users/jaybeecave/go/src/github.com/nerdynz/skeleton/spa/.nuxt/dist/server/server.mjs:1870:3)
Server Side Rendering Error: /Users/jaybeecave/go/src/github.com/nerdynz/skeleton/spa/node_modules/vue-class-component/dist/vue-class-component.esm-bundler.js:6
import { ref, proxyRefs } from 'vue';
```
